baseURL = 'https://pagefind.app/'
languageCode = 'en-us'
title = 'Pagefind'
summaryLength = 30
disableKinds = ["taxonomyTerm"]

[markup]
highlight.noClasses = false

[markup.goldmark.renderer]
# ensures html inside markdown is allowed to render
unsafe = true

[[module.imports]]
path = 'github.com/bglw/alto-as-module'
